version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: hellojade_db
    environment:
      POSTGRES_DB: hellojade
      POSTGRES_USER: hellojade_user
      POSTGRES_PASSWORD: hellojade_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U hellojade_user -d hellojade"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: hellojade_cache
    ports:
      - "6379:6379"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: 